version: '3'
services:
  mongodb:
    image : mongo
    restart: always
    ports:
     - "27016:27016"
    container_name: mongo-container
    network_mode: host
  spring:
    image: spring-boot
    restart: always
    build: muzix-docker/
    container_name: spring-docker
    network_mode: host
  zuul:
    image: zuul
    restart: always
    build: zuulservice/
    container_name: zuul-docker
    network_mode: host
  eureka:
    image: eureka
    restart: always
    build: Eureka-server/
    container_name: eureka-docker
    network_mode: host
  config:
    image: config
    restart: always
    build: config-server
    container_name: config-docker
    network_mode: host